### ISSUE TITLE
Create resources PR for new Amazon resources

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_methods#263] opened 2020-09-24 14:48 UTC
We should discuss creating a resources library for gnomAD files hosted on Amazon for any users that are writing pipelines on AWS

**Comment by nawatts** [comment] 2020-09-24 14:54
As long as the buckets on each cloud provider keeps the same structure, resource classes could accept a cloud provider and path (relative to the bucket root) and construct the absolute URL based on those by joining the appropriate URL schema and bucket name for the selected provider and the path (which does not change between providers).

**Comment by nawatts** [comment] 2021-05-05 18:25
Closing this as a duplicate of #255.

**Closed by nawatts** 2021-05-05 18:25 UTC
